spring.application.name=hm-auth-service
server.servlet.context-path=/fosys
server.port=8881

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true


# Security (Basic auth for actuator endpoints)
#spring.security.user.name=admin
#spring.security.user.password=admin

#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=false
#springdoc.swagger-ui.override-with-gateway-url=true